export interface Todo {
  Id?: number; // Optional as it will be autogenerated
  Name: string; // Required
  Description?: string; // Optional
  Done?: boolean; // Optional, defaulting to false
  Expenses?: number; // Optional
  Created?: number; // Optional, autogenerated
}