export interface Todo {
  Id?: number; // Optional, as it will be autogenerated by the database
  Name: string; // Required, as a task must have a name
  Description?: string; // Optional, as a task can be simple enough to not need a description
  Done?: boolean; // Optional, defaulting to false if not provided, as it is a new task
  Expenses?: number; // Optional, as a task can be done without any expenses
  Created?: number; // Optional, autogenerated as the current timestamp
}
